const products = [
  {
    _id: '1',
    name: "Air Jordan 1 Retro High OG 'Chicago' 2015",
    image: '/images/jordan_1_chicago.jpg',
    description:
      "The Air Jordan 1 Retro High OG 'Chicago' 2015 colorway was designed to avoid Jordan's $5,000-per game fines from the NBA after the original black and red colorway was banned. The 'Chicago' was first retroed in 1994 and stayed true to the 1985 design. Further retros were released in 2013 with small changes to the design, and again in 2015 with the original branding details: the Nike Air logo on the tongue and the original clean heel without the Jumpman logo.",
    brand: 'Air Jordan',
    category: 'Footwear',
    price: '2,000.99',
    countInStock: 1,
    rating: 4.8,
    numReviews: 123,
    size: '10.5 US',
  },
  {
    _id: '2',
    name: "Yeezy Boost 700 'Wave Runner'",
    image: '/images/yeezy_boost_700.jpg',
    description:
      'This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017, following a public debut earlier in the year as part of the Yeezy Season 5 runway show. The sneaker’s retro-inspired lines worked in tandem with a chunky silhouette reminiscent of an earlier era. A mesh base is finished in grey on the quarter panels and bright blue and teal on the forefoot. Suede overlays arrive on the toe and heel accented grey leather eyestays. Other details include neon green laces, a bulky white midsole, and pops of black and bright orange.',
    brand: 'Yeezy',
    category: 'Footwear',
    price: 350.99,
    countInStock: 1,
    rating: 4.3,
    numReviews: 8,
    size: '11 US',
  },
  {
    _id: '3',
    name: "Off White x Air Jordan 1 Retro High OG 'UNC'",
    image: '/images/offwhite_airjordanogunc.webp',
    description:
      'Inspired by Michael Jordan’s alma mater, the Off-White x Air Jordan 1 Retro High OG ‘UNC’ carries a classic two-tone composition, filtered through Virgil Abloh’s unique design prism. The process involves taking a white leather base with dark powder blue overlays and adding embellishments that convey an expressive, handmade quality. They include detached Wings, a floating Swoosh, and lines of text on the medial-side quarter panel delineating the taxonomy of the shoe.',
    brand: 'Air Jordan',
    category: 'Footwear',
    price: '3,496.99',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
    size: '9 US',
  },
  {
    _id: '4',
    name: "Yeezy Boost 350 V2 CMPCT 'Slate Carbon'",
    image: '/images/slatecarbonyeezy.jpg',
    description:
      'The Yeezy Boost 350 v2 ‘Slate Carbon’ dresses the casual sneaker in a patterned Primeknit upper in neutral shades of black, grey, and tan. The slip-on build is secured with no-tie rope laces and a sock-like cuff, which offers lightweight support with a full range of motion. Yeezy branding is limited to the sockliner. Responsive cushioning is provided by a full-length Boost midsole, wrapped in a TPU cage and exposed through cut-outs in the rubber outsole.',
    brand: 'Yeezy',
    category: 'Footwear',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
    size: '10 US',
  },
  {
    _id: '5',
    name: "Air Jordan 5 Retro SE 'Easter'",
    image: '/images/aj5easter.jpg',
    description:
      'The Air Jordan 5 Retro SE ‘Easter’ gives the classic silhouette a pastel makeover in keeping with the springtime holiday. Finished in Regal Pink, the smooth nubuck upper features traditional AJ5 elements, including TPU eyelets, lace locks, and quarter-panel netting. Embroidered Jumpman branding lands on the heel overlay and pale green padded tongue. Inside the shoe, the sockliner displays vibrant bands of color in a nod to the tradition of dyed Easter eggs. The sneaker sits atop an Air-assisted polyurethane midsole, accented with speckled shark-tooth detailing and supported by a green-tinged translucent rubber outsole that glows in the dark.',
    brand: 'Air Jordan',
    category: 'Footwear',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
    size: '13 US',
  },
  {
    _id: '6',
    name: "Blazer Mid '77 Vintage 'White Black'",
    image: '/images/blazer.jpg',
    description:
      'As one of the first Nike basketball sneakers ever released, the Nike Blazer has a long heritage. The Nike Blazer Mid ’77 Vintage ‘White Black’ pays homage to its history with an old-school look. The upper comes in white leather, with an OG Swoosh taking up the side, and a deconstructed tongue with vintage branding. Two forefoot overlays come in a hairy tonal suede, and the rear branding features a distressed ‘NIKE’ logo.',
    brand: 'Nike',
    category: 'Footwear',
    price: 89.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
    size: '8 US',
  },
]

export default products
